In [1]:
import numpy as np

index = np.load("/home/jovyan/Sample_Based_Extension/WUSTL/best_defense_indices.npy", allow_pickle=True)
index

array([['baseline', 0, 'Def1-11 Combined', 0.9999916231419081,
        0.9951091814583067, array([2, 2, 2, ..., 2, 2, 2])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9999916231419081,
        0.9951091814583067, array([2, 2, 2, ..., 2, 2, 2])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9998827239867143,
        0.9600649800293866, array([1, 1, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9996984331086939,
        0.9305545272093338, array([3, 3, 3, ..., 3, 3, 3])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.9984796002563319,
        0.7518383136072314, array([5, 5, 5, ..., 5, 5, 5])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9999916231419081,
        0.9951091814583067, array([2, 2, 2, ..., 2, 2, 2])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9998701586995765,
        0.939002641264322, array([1, 1, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9971518682487759,
        0.8894642081911899, array([3, 3, 3, ..., 3, 3, 3])],
       ['FGSM', 0.3, 'Def

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    ("DF", [0.1]),
    # ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    # ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [4]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1 and attack_name!= "CaFA" and attack_name!= "AutoPGD":
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

unique_labels, counts = np.unique(y_label_0_1, return_counts=True)
print(unique_labels, counts)
valid_labels = unique_labels[counts > 4]
mask = np.isin(y_label_0_1, valid_labels)
x_test_adv_0_1 = x_test_adv_0_1[mask]
y_label_0_1 = y_label_0_1[mask]
print(np.unique(y_label_0_1, return_counts = True))

[ 1  2  3  4  5  6  7  8  9 10] [955020     14 240816     19   4000 467856      3   1083     52   2408]
(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10]), array([955020,     14, 240816,     19,   4000, 467856,   1083,     52,
         2408]))


In [5]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '8' encode 6
defense '9' encode 7
defense '10' encode 8


In [6]:
# Collect 10% of eps = 0.1 data
from sklearn.model_selection import train_test_split

_, X_10, _ , y_10 = train_test_split(x_test_adv_0_1, y_label_0_1, test_size=0.1, stratify=y_label_0_1, random_state=42)


In [7]:
X_10.shape

(167127, 42)

In [8]:
from xgboost import XGBClassifier

print('xgb')
xgb10 = XGBClassifier()
xgb10.fit(X_10, y_10)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf10 = RandomForestClassifier()
rf10.fit(X_10, y_10)

# print("DT")
# from sklearn.tree import DecisionTreeClassifier
# dt10 = DecisionTreeClassifier()
# dt10.fit(X_10, y_10)

xgb
RF


RandomForestClassifier()

In [9]:
import time
import numpy as np

y_test = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

In [10]:


base_path_template = "/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack}_eps_{eps}.npy"

from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

    y_pred = xgb10.predict(X)
    print(y_pred.shape)
    y_pred = label_encoder.inverse_transform(y_pred)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/XGB_Exclude2Attack/WUSTL_Input10/x_test_adv_{attack_name}_Def{class_num}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/XGB_Exclude2Attack/WUSTL_Input10/y_test_adv_{attack_name}_Def{class_num}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(238753,)
[1 2 6] [     4      3 238746]
(4, 42) (4,)
Save 1 to baseline_Def1.npy
(3, 42) (3,)
Save 2 to baseline_Def2.npy
(238746, 42) (238746,)
Save 6 to baseline_Def6.npy
Execution Time: 1.272395 seconds
(716259,)
[ 1  3  4  5  6 10] [482727 211570     52    517  19869   1524]
(482727, 42) (482727,)
Save 1 to BIM_Def1.npy
(211570, 42) (211570,)
Save 3 to BIM_Def3.npy
(52, 42) (52,)
Save 4 to BIM_Def4.npy
(517, 42) (517,)
Save 5 to BIM_Def5.npy
(19869, 42) (19869,)
Save 6 to BIM_Def6.npy
(1524, 42) (1524,)
Save 10 to BIM_Def10.npy
Execution Time: 5.216316 seconds
(716259,)
[ 1  3  4  5  6  8  9 10] [455159   5472     27   7963  21410   3672     10 222546]
(455159, 42) (455159,)
Save 1 to FGSM_Def1.npy
(5472, 42) (5472,)
Save 3 to FGSM_Def3.npy
(27, 42) (27,)
Save 4 to FGSM_Def4.npy
(7963, 42) (7963,)
Save 5 to FGSM_Def5.npy
(21410, 42) (21410,)
Save 6 to FGSM_Def6.npy
(3672, 42) (3672,)
Save 8 to FGSM_Def8.npy
(10, 42) (10,)
Save 9 to FGSM_Def9.npy
(222546, 42) (222546,)
Save 10 to F

In [11]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

    y_pred = rf10.predict(X)
    print(y_pred.shape)
    y_pred = label_encoder.inverse_transform(y_pred)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/RF_Exclude2Attack/WUSTL_Input10/x_test_adv_{attack_name}_Def{class_num}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/RF_Exclude2Attack/WUSTL_Input10/y_test_adv_{attack_name}_Def{class_num}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(238753,)
[2 6] [     1 238752]
(1, 42) (1,)
Save 2 to baseline_Def2.npy
(238752, 42) (238752,)
Save 6 to baseline_Def6.npy
Execution Time: 4.184877 seconds
(716259,)
[1 3 5 6] [410972  36676     80 268531]
(410972, 42) (410972,)
Save 1 to BIM_Def1.npy
(36676, 42) (36676,)
Save 3 to BIM_Def3.npy
(80, 42) (80,)
Save 5 to BIM_Def5.npy
(268531, 42) (268531,)
Save 6 to BIM_Def6.npy
Execution Time: 12.784103 seconds
(716259,)
[ 1  3  5  6 10] [435683  22622   1203 256746      5]
(435683, 42) (435683,)
Save 1 to FGSM_Def1.npy
(22622, 42) (22622,)
Save 3 to FGSM_Def3.npy
(1203, 42) (1203,)
Save 5 to FGSM_Def5.npy
(256746, 42) (256746,)
Save 6 to FGSM_Def6.npy
(5, 42) (5,)
Save 10 to FGSM_Def10.npy
Execution Time: 36.876518 seconds
(716259,)
[1 3 5 6] [410972  36676     80 268531]
(410972, 42) (410972,)
Save 1 to PGD_Def1.npy
(36676, 42) (36676,)
Save 3 to PGD_Def3.npy
(80, 42) (80,)
Save 5 to PGD_Def5.npy
(268531, 42) (268531,)
Save 6 to PGD_Def6.npy
Execution Time: 65.885934 seconds
(716259,

In [12]:
# from sklearn.model_selection import train_test_split

# for attack_name, epsilons in attack_models:
#     start_time = time.time()
#     all_adv_examples = []
#     all_y = []
    
#     if attack_name != "baseline":
#         for epsilon in epsilons:
#             filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
#             x_test_adv = np.load(filename)
#             all_adv_examples.append(x_test_adv)
#             all_y.append(y_test)
    
#         X = np.concatenate(all_adv_examples, axis=0)
#         y = np.concatenate(all_y, axis=0)
#     else:
#         X = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/x_test.npy')
#         y = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

#     y_pred = dt10.predict(X)
#     print(y_pred.shape)
#     y_pred = label_encoder.inverse_transform(y_pred)
#     unique_classes, count = np.unique(y_pred, return_counts=True)
#     print(unique_classes, count)
#     for class_num in unique_classes:
#         indices = np.where(y_pred == class_num)[0]
#         X_class = X[indices]
#         y_class = y[indices]
#         print(X_class.shape, y_class.shape)
    
#         x_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/DT_Exclude2Attack/WUSTL_Input10/x_test_adv_{attack_name}_Def{class_num}.npy"
#         y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/DT_Exclude2Attack/WUSTL_Input10/y_test_adv_{attack_name}_Def{class_num}.npy"
        
#         np.save(x_filename, X_class)
#         np.save(y_filename, y_class)
    
#         print(f"Save {class_num} to {attack_name}_Def{class_num}.npy")

#     end_time = time.time()
#     result = end_time - start_time
#     print(f"Execution Time: {result:.6f} seconds")
    

In [13]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}10")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/{m_name}_Exclude2Attack/WUSTL_Input10/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [14]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input10_Exclude2Attack.csv")

In [15]:
all_attack_list

0       1    2       3     4      5       6   7     8    9       10  \
0   XGB10       4    3       0     0      0  238746   0     0    0       0   
1   XGB10  482727    0  211570    52    517   19869   0     0    0    1524   
2   XGB10  455159    0    5472    27   7963   21410   0  3672   10  222546   
3   XGB10  482727    0  211570    52    517   19869   0     0    0    1524   
4   XGB10      91    0    5659    34  10377  688278   0  3244  162    8414   
5   XGB10  292447    0  137490  7982    523  276239   0   133  316    1129   
6   XGB10      12    9       0     0      0  716238   0     0    0       0   
7   XGB10  353874  102   13908     0   1183  343197   0     0  390    3605   
8   XGB10  209244    0  470520    24    353   35819   0     0    0     299   
9   XGB10  618357    0   39250   206     75   58235   0     1    0     135   
10   RF10       0    1       0     0      0  238752   0     0    0       0   
11   RF10  410972    0   36676     0     80  268531   0     0    0       0   
12   RF10  435683    0   22622     0   1203  256746   0     0    0       5   
13   RF10  410972    0   36676     0     80  268531   0     0    0       0   
14   RF10      32    0    5501    35   9102  687987   0  3624  201    9777   
15   RF10  365202    0   42404     0    204  308449   0     0    0       0   
16   RF10       0    3       0     0      0  716256   0     0    0       0   
17   RF10  251824    0       7     0      0  464428   0     0    0       0   
18   RF10   21973    0  452500     0     10  241776   0     0    0       0   
19   RF10  319233    0   31018     7   2412  363589   0     0    0       0   
20   DT10       0    0       0     0      0       0   0     0    0       0   
21   DT10       0    0       0     0      0       0   0     0    0       0   
22   DT10       0    0       0     0      0       0   0     0    0       0   
23   DT10       0    0       0     0      0       0   0     0    0       0   
24   DT10       0    0       0     0      0       0   0     0    0       0   
25   DT10       0    0       0     0      0       0   0     0    0       0   
26   DT10       0    0       0     0      0       0   0     0    0       0   
27   DT10       0    0       0     0      0       0   0     0    0       0   
28   DT10       0    0       0     0      0       0   0     0    0       0   
29   DT10       0    0       0     0      0       0   0     0    0       0   

    11      12  
0    0  238753  
1    0  716259  
2    0  716259  
3    0  716259  
4    0  716259  
5    0  716259  
6    0  716259  
7    0  716259  
8    0  716259  
9    0  716259  
10   0  238753  
11   0  716259  
12   0  716259  
13   0  716259  
14   0  716259  
15   0  716259  
16   0  716259  
17   0  716259  
18   0  716259  
19   0  716259  
20   0       0  
21   0       0  
22   0       0  
23   0       0  
24   0       0  
25   0       0  
26   0       0  
27   0       0  
28   0       0  
29   0       0