In [1]:
import numpy as np

index = np.load("/home/jovyan/Sample_Based_Extension/UNSW/best_defense_indices.npy", allow_pickle=True)
index

array([['baseline', 0, 'Def1-11 Combined', 0.9923313825446824,
        0.9911800925969834, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9891551359556379,
        0.987484040917074, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9746251239350361,
        0.9705688736459472, array([1, 6, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9594545980995165,
        0.9538946564599001, array([6, 6, 6, ..., 6, 6, 6])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.919233840187416,
        0.9113183206844415, array([6, 6, 6, ..., 6, 6, 6])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9889357819094331,
        0.9872271983425641, array([9, 3, 9, ..., 9, 9, 9])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9680708250344385,
        0.9628361221532343, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9461968395469023,
        0.9384213027985543, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.3, 'Def1

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    ("DF", [0.1]),
    ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [3]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1:
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '7' encode 6
defense '8' encode 7
defense '9' encode 8
defense '10' encode 9
defense '11' encode 10


In [5]:
# Collect 10% of eps = 0.1 data
from sklearn.model_selection import train_test_split

_, X_10, _ , y_10 = train_test_split(x_test_adv_0_1, y_label_0_1, test_size=0.1, stratify=y_label_0_1, random_state=42)


In [6]:
# from xgboost import XGBClassifier

# print('xgb')
# xgb10 = XGBClassifier()
# xgb10.fit(X_10, y_10)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf10 = RandomForestClassifier()
rf10.fit(X_10, y_10)

# print("DT")
# from sklearn.tree import DecisionTreeClassifier
# dt10 = DecisionTreeClassifier()
# dt10.fit(X_10, y_10)

xgb
RF
DT


DecisionTreeClassifier()

In [ ]:
import time
import numpy as np

y_test = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

In [7]:


# base_path_template = "/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack}_eps_{eps}.npy"

# from sklearn.model_selection import train_test_split

# for attack_name, epsilons in attack_models:
#     start_time = time.time()
#     all_adv_examples = []
#     all_y = []
    
#     if attack_name != "baseline":
#         for epsilon in epsilons:
#             filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
#             x_test_adv = np.load(filename)
#             all_adv_examples.append(x_test_adv)
#             all_y.append(y_test)
    
#         X = np.concatenate(all_adv_examples, axis=0)
#         y = np.concatenate(all_y, axis=0)
#     else:
#         X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
#         y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

#     y_pred = xgb10.predict(X)
#     print(y_pred.shape)
#     unique_classes, count = np.unique(y_pred, return_counts=True)
#     print(unique_classes, count)
#     for class_num in unique_classes:
#         indices = np.where(y_pred == class_num)[0]
#         X_class = X[indices]
#         y_class = y[indices]
#         print(X_class.shape, y_class.shape)
    
#         x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB/UNSW_Input10/x_test_adv_{attack_name}_Def{class_num+1}.npy"
#         y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB/UNSW_Input10/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
#         np.save(x_filename, X_class)
#         np.save(y_filename, y_class)
    
#         print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

#     end_time = time.time()
#     result = end_time - start_time
#     print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [25185   194  2428   894    41  1703   170 83100   186    70]
(25185, 56) (25185,)
Save 0 to baseline_Def1.npy
(194, 56) (194,)
Save 1 to baseline_Def2.npy
(2428, 56) (2428,)
Save 2 to baseline_Def3.npy
(894, 56) (894,)
Save 3 to baseline_Def4.npy
(41, 56) (41,)
Save 4 to baseline_Def5.npy
(1703, 56) (1703,)
Save 5 to baseline_Def6.npy
(170, 56) (170,)
Save 7 to baseline_Def8.npy
(83100, 56) (83100,)
Save 8 to baseline_Def9.npy
(186, 56) (186,)
Save 9 to baseline_Def10.npy
(70, 56) (70,)
Save 10 to baseline_Def11.npy
Execution Time: 0.732352 seconds
(341913,)
[ 0  1  2  3  4  5  6  7  8  9 10] [121884    251   1095    904    211 171414      2    109  45923     26
     94]
(121884, 56) (121884,)
Save 0 to BIM_Def1.npy
(251, 56) (251,)
Save 1 to BIM_Def2.npy
(1095, 56) (1095,)
Save 2 to BIM_Def3.npy
(904, 56) (904,)
Save 3 to BIM_Def4.npy
(211, 56) (211,)
Save 4 to BIM_Def5.npy
(171414, 56) (171414,)
Save 5 to BIM_Def6.npy
(2, 56) (2,)
Save 6 to 

In [8]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = rf10.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF/UNSW_Input10/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF/UNSW_Input10/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [25670   157  2296   942    59  2567   170 81884   173    53]
(25670, 56) (25670,)
Save 0 to baseline_Def1.npy
(157, 56) (157,)
Save 1 to baseline_Def2.npy
(2296, 56) (2296,)
Save 2 to baseline_Def3.npy
(942, 56) (942,)
Save 3 to baseline_Def4.npy
(59, 56) (59,)
Save 4 to baseline_Def5.npy
(2567, 56) (2567,)
Save 5 to baseline_Def6.npy
(170, 56) (170,)
Save 7 to baseline_Def8.npy
(81884, 56) (81884,)
Save 8 to baseline_Def9.npy
(173, 56) (173,)
Save 9 to baseline_Def10.npy
(53, 56) (53,)
Save 10 to baseline_Def11.npy
Execution Time: 1.939991 seconds
(341913,)
[0 1 2 3 4 5 8] [134361      1    403    564      4 178246  28334]
(134361, 56) (134361,)
Save 0 to BIM_Def1.npy
(1, 56) (1,)
Save 1 to BIM_Def2.npy
(403, 56) (403,)
Save 2 to BIM_Def3.npy
(564, 56) (564,)
Save 3 to BIM_Def4.npy
(4, 56) (4,)
Save 4 to BIM_Def5.npy
(178246, 56) (178246,)
Save 5 to BIM_Def6.npy
(28334, 56) (28334,)
Save 8 to BIM_Def9.npy
Execution Time: 2.799659 seconds
(341

In [9]:
# from sklearn.model_selection import train_test_split

# for attack_name, epsilons in attack_models:
#     start_time = time.time()
#     all_adv_examples = []
#     all_y = []
    
#     if attack_name != "baseline":
#         for epsilon in epsilons:
#             filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
#             x_test_adv = np.load(filename)
#             all_adv_examples.append(x_test_adv)
#             all_y.append(y_test)
    
#         X = np.concatenate(all_adv_examples, axis=0)
#         y = np.concatenate(all_y, axis=0)
#     else:
#         X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
#         y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

#     y_pred = dt10.predict(X)
#     print(y_pred.shape)
#     unique_classes, count = np.unique(y_pred, return_counts=True)
#     print(unique_classes, count)
#     for class_num in unique_classes:
#         indices = np.where(y_pred == class_num)[0]
#         X_class = X[indices]
#         y_class = y[indices]
#         print(X_class.shape, y_class.shape)
    
#         x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT/UNSW_Input10/x_test_adv_{attack_name}_Def{class_num+1}.npy"
#         y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT/UNSW_Input10/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
#         np.save(x_filename, X_class)
#         np.save(y_filename, y_class)
    
#         print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

#     end_time = time.time()
#     result = end_time - start_time
#     print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [31440   370  2269  1340   158  3566   359 73997   323   149]
(31440, 56) (31440,)
Save 0 to baseline_Def1.npy
(370, 56) (370,)
Save 1 to baseline_Def2.npy
(2269, 56) (2269,)
Save 2 to baseline_Def3.npy
(1340, 56) (1340,)
Save 3 to baseline_Def4.npy
(158, 56) (158,)
Save 4 to baseline_Def5.npy
(3566, 56) (3566,)
Save 5 to baseline_Def6.npy
(359, 56) (359,)
Save 7 to baseline_Def8.npy
(73997, 56) (73997,)
Save 8 to baseline_Def9.npy
(323, 56) (323,)
Save 9 to baseline_Def10.npy
(149, 56) (149,)
Save 10 to baseline_Def11.npy
Execution Time: 0.187604 seconds
(341913,)
[ 0  1  2  3  4  5  6  7  8  9 10] [143564   1836  11472  16035   3081 106194   3594  25812  29752    258
    315]
(143564, 56) (143564,)
Save 0 to BIM_Def1.npy
(1836, 56) (1836,)
Save 1 to BIM_Def2.npy
(11472, 56) (11472,)
Save 2 to BIM_Def3.npy
(16035, 56) (16035,)
Save 3 to BIM_Def4.npy
(3081, 56) (3081,)
Save 4 to BIM_Def5.npy
(106194, 56) (106194,)
Save 5 to BIM_Def6.npy
(3594, 

In [10]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}10")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/{m_name}/UNSW_Input10/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [11]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input10.csv")

In [12]:
all_attack_list

0       1     2      3      4     5       6     7      8       9   \
0   XGB20   25185   194   2428    894    41    1703     0    170   83100   
1   XGB20  121884   251   1095    904   211  171414     2    109   45923   
2   XGB20  109519    52    869   1325    89  183261     0    648   46109   
3   XGB20  121884   251   1095    904   211  171414     2    109   45923   
4   XGB20   75312   532   2318    353   333  243612   669  16979    1471   
5   XGB20  145682   559   4490   2434   259  158995     0    404   28598   
6   XGB20   70986   558   6689   2643   115    4946     0    510  254774   
7   XGB20  252910    93    631   1025    75   19619     0    126   65894   
8   XGB20  122274   362    494    685   141  176305     2     10   41606   
9   XGB20  131574    65   1155    928   293  162136     0     47   45653   
10   RF20   25670   157   2296    942    59    2567     0    170   81884   
11   RF20  134361     1    403    564     4  178246     0      0   28334   
12   RF20  120360     0    410    445     1  192665     0    204   27828   
13   RF20  134361     1    403    564     4  178246     0      0   28334   
14   RF20   75700   500   2331    292   177  244244   537  16069    1764   
15   RF20  130983   333   4048   2364   162  182140     0    438   21013   
16   RF20   72471   444   6429   2614   170    7037     0    510  251631   
17   RF20  255466    30    425    881    11   15474     0    101   68316   
18   RF20  125695     1    149    453    20  188582     0      0   27013   
19   RF20  121252     0    392    443    16  190677     0      0   29133   
20   DT20   31440   370   2269   1340   158    3566     0    359   73997   
21   DT20  143564  1836  11472  16035  3081  106194  3594  25812   29752   
22   DT20  127653  1524   6165   7922   976  146130  8370  12674   28824   
23   DT20  143564  1836  11472  16035  3081  106194  3594  25812   29752   
24   DT20   71536   755   3313    714  2276  237077  2409  19832    3211   
25   DT20  137460  1499  11316  15857  3346  111326  4287  29599   25918   
26   DT20   84515  1157   6799   4183   465   10074     0   1080  232421   
27   DT20  241653   537    910   3008  1899   24851     0   1225   59518   
28   DT20  166455  3092   9740  10190  3729   90135   694  31252   25345   
29   DT20  148847  2310   7456   8454  1385  115496  8825  23146   25319   

      10    11      12  
0    186    70  113971  
1     26    94  341913  
2      5    36  341913  
3     26    94  341913  
4    258    76  341913  
5    308   184  341913  
6    495   197  341913  
7   1183   357  341913  
8      4    30  341913  
9      7    55  341913  
10   173    53  113971  
11     0     0  341913  
12     0     0  341913  
13     0     0  341913  
14   222    77  341913  
15   288   144  341913  
16   448   159  341913  
17   913   296  341913  
18     0     0  341913  
19     0     0  341913  
20   323   149  113971  
21   258   315  341913  
22   205  1470  341913  
23   258   315  341913  
24   496   294  341913  
25   639   666  341913  
26   880   339  341913  
27  5003  3309  341913  
28   258  1023  341913  
29   234   441  341913