In [1]:
import numpy as np

index = np.load("/home/jovyan/Sample_Based_Extension/UNSW/best_defense_indices.npy", allow_pickle=True)
index

array([['baseline', 0, 'Def1-11 Combined', 0.9923313825446824,
        0.9911800925969834, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9891551359556379,
        0.987484040917074, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9746251239350361,
        0.9705688736459472, array([1, 6, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9594545980995165,
        0.9538946564599001, array([6, 6, 6, ..., 6, 6, 6])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.919233840187416,
        0.9113183206844415, array([6, 6, 6, ..., 6, 6, 6])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9889357819094331,
        0.9872271983425641, array([9, 3, 9, ..., 9, 9, 9])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9680708250344385,
        0.9628361221532343, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9461968395469023,
        0.9384213027985543, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.3, 'Def1

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    # ("DF", [0.1]),
    # ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    # ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [3]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1 and attack_name!= "CaFA" and attack_name!= "AutoPGD" and attack_name!= "DF":
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '7' encode 6
defense '8' encode 7
defense '9' encode 8
defense '10' encode 9
defense '11' encode 10


In [5]:
# Collect 50% of eps = 0.1 data
from sklearn.model_selection import train_test_split

_, X_50, _, y_50 = train_test_split(x_test_adv_0_1, y_label_0_1, test_size=0.5, stratify=y_label_0_1, random_state=42)

In [6]:
X_50.shape

(341913, 56)

In [7]:
from xgboost import XGBClassifier

print('xgb')
xgb50 = XGBClassifier()
xgb50.fit(X_50, y_50)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf50 = RandomForestClassifier()
rf50.fit(X_50, y_50)

print("DT")
from sklearn.tree import DecisionTreeClassifier
dt50 = DecisionTreeClassifier()
dt50.fit(X_50, y_50)

xgb
RF
DT


DecisionTreeClassifier()

In [8]:
import time
import numpy as np

y_test = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

base_path_template = "/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack}_eps_{eps}.npy"

from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = xgb50.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_Exclude3Attack/UNSW_Input50/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_Exclude3Attack/UNSW_Input50/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   211    291   2058   2195     49    419    168 108276    249     55]
(211, 56) (211,)
Save 0 to baseline_Def1.npy
(291, 56) (291,)
Save 1 to baseline_Def2.npy
(2058, 56) (2058,)
Save 2 to baseline_Def3.npy
(2195, 56) (2195,)
Save 3 to baseline_Def4.npy
(49, 56) (49,)
Save 4 to baseline_Def5.npy
(419, 56) (419,)
Save 5 to baseline_Def6.npy
(168, 56) (168,)
Save 7 to baseline_Def8.npy
(108276, 56) (108276,)
Save 8 to baseline_Def9.npy
(249, 56) (249,)
Save 9 to baseline_Def10.npy
(55, 56) (55,)
Save 10 to baseline_Def11.npy
Execution Time: 0.279366 seconds
(341913,)
[ 0  1  2  3  4  5  7  8  9 10] [218191    331   2024   3642    419   4895     86 112246     20     59]
(218191, 56) (218191,)
Save 0 to BIM_Def1.npy
(331, 56) (331,)
Save 1 to BIM_Def2.npy
(2024, 56) (2024,)
Save 2 to BIM_Def3.npy
(3642, 56) (3642,)
Save 3 to BIM_Def4.npy
(419, 56) (419,)
Save 4 to BIM_Def5.npy
(4895, 56) (4895,)
Save 5 to BIM_Def6.npy
(86, 56) (86,)
Save 7 to BIM

In [9]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = rf50.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_Exclude3Attack/UNSW_Input50/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_Exclude3Attack/UNSW_Input50/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   356    322   2118   1915     61    813    168 107919    221     78]
(356, 56) (356,)
Save 0 to baseline_Def1.npy
(322, 56) (322,)
Save 1 to baseline_Def2.npy
(2118, 56) (2118,)
Save 2 to baseline_Def3.npy
(1915, 56) (1915,)
Save 3 to baseline_Def4.npy
(61, 56) (61,)
Save 4 to baseline_Def5.npy
(813, 56) (813,)
Save 5 to baseline_Def6.npy
(168, 56) (168,)
Save 7 to baseline_Def8.npy
(107919, 56) (107919,)
Save 8 to baseline_Def9.npy
(221, 56) (221,)
Save 9 to baseline_Def10.npy
(78, 56) (78,)
Save 10 to baseline_Def11.npy
Execution Time: 1.179449 seconds
(341913,)
[ 0  1  2  3  4  5  7  8  9 10] [216230    377   2469   2686    216   4687     94 115131     13     10]
(216230, 56) (216230,)
Save 0 to BIM_Def1.npy
(377, 56) (377,)
Save 1 to BIM_Def2.npy
(2469, 56) (2469,)
Save 2 to BIM_Def3.npy
(2686, 56) (2686,)
Save 3 to BIM_Def4.npy
(216, 56) (216,)
Save 4 to BIM_Def5.npy
(4687, 56) (4687,)
Save 5 to BIM_Def6.npy
(94, 56) (94,)
Save 7 to BIM

In [10]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = dt50.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_Exclude3Attack/UNSW_Input50/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_Exclude3Attack/UNSW_Input50/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   488    555   2780   2121     98   1295    354 105770    310    200]
(488, 56) (488,)
Save 0 to baseline_Def1.npy
(555, 56) (555,)
Save 1 to baseline_Def2.npy
(2780, 56) (2780,)
Save 2 to baseline_Def3.npy
(2121, 56) (2121,)
Save 3 to baseline_Def4.npy
(98, 56) (98,)
Save 4 to baseline_Def5.npy
(1295, 56) (1295,)
Save 5 to baseline_Def6.npy
(354, 56) (354,)
Save 7 to baseline_Def8.npy
(105770, 56) (105770,)
Save 8 to baseline_Def9.npy
(310, 56) (310,)
Save 9 to baseline_Def10.npy
(200, 56) (200,)
Save 10 to baseline_Def11.npy
Execution Time: 0.071546 seconds
(341913,)
[ 0  1  2  3  4  5  6  7  8  9 10] [195332   1206   6172  14879  11833   9652      3   1642  99678    603
    913]
(195332, 56) (195332,)
Save 0 to BIM_Def1.npy
(1206, 56) (1206,)
Save 1 to BIM_Def2.npy
(6172, 56) (6172,)
Save 2 to BIM_Def3.npy
(14879, 56) (14879,)
Save 3 to BIM_Def4.npy
(11833, 56) (11833,)
Save 4 to BIM_Def5.npy
(9652, 56) (9652,)
Save 5 to BIM_Def6.npy
(3, 5

In [11]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}50")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/{m_name}_Exclude3Attack/UNSW_Input50/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [12]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input50_Exclude3Attack.csv")

In [13]:
all_attack_list

0       1     2     3      4      5     6   7     8       9     10  \
0   XGB50     211   291  2058   2195     49   419   0   168  108276   249   
1   XGB50  218191   331  2024   3642    419  4895   0    86  112246    20   
2   XGB50  221198    99  1643   5187    475  2688   0   406  110145    14   
3   XGB50  218191   331  2024   3642    419  4895   0    86  112246    20   
4   XGB50  299583    65  2850   4592   1081   905   0     0   32804    29   
5   XGB50  203521   980  4737   6984    386  1893   0   486  122182   582   
6   XGB50     645   841  6333   6040    143  1200   0   503  325380   662   
7   XGB50   81316    39  1129   1427     26   124   0    18  257773    22   
8   XGB50  212565   621  1639   5957    593  2363   0    11  118102     9   
9   XGB50  216821   119  2133   5306    869  4630   0    41  111903     7   
10   RF50     356   322  2118   1915     61   813   0   168  107919   221   
11   RF50  216230   377  2469   2686    216  4687   0    94  115131    13   
12   RF50  216899    39  2010   4860    482  3518   0   396  113615    18   
13   RF50  216230   377  2469   2686    216  4687   0    94  115131    13   
14   RF50  321243    10   707   1678     38  1457   0     0   16668    18   
15   RF50  203492  1134  5506   6737    333  2905   0   492  120524   565   
16   RF50    1056   924  6552   5357    183  2238   0   504  324245   622   
17   RF50  116860    24   282    286      0   105   0     6  224333    14   
18   RF50  214206   573  1978   5610    274  4898   0     1  114346    16   
19   RF50  214317    65  2593   4854    567  5041   0     1  114406    15   
20   DT50     488   555  2780   2121     98  1295   0   354  105770   310   
21   DT50  195332  1206  6172  14879  11833  9652   3  1642   99678   603   
22   DT50  189546  1337  5231  18591   8549  9363  13  2808  104677   856   
23   DT50  195332  1206  6172  14879  11833  9652   3  1642   99678   603   
24   DT50  221472  3167  4561  30163  19032  4152   0  2471   50958  4683   
25   DT50  183417  3162  9943  21868  10901  5773   1  2132  102478  1242   
26   DT50    1559  1613  8344   6140    289  3511   2  1043  317926   906   
27   DT50   91084   170  5235  90935   1758   857   0   262  151326   175   
28   DT50  198395  2652  4774  15529  11605  6996   4  1130  100278   237   
29   DT50  196736  1702  4303  13895   9714  8169   4  2832  103282   602   

      11      12  
0     55  113971  
1     59  341913  
2     58  341913  
3     59  341913  
4      4  341913  
5    162  341913  
6    166  341913  
7     39  341913  
8     53  341913  
9     84  341913  
10    78  113971  
11    10  341913  
12    76  341913  
13    10  341913  
14    94  341913  
15   225  341913  
16   232  341913  
17     3  341913  
18    11  341913  
19    54  341913  
20   200  113971  
21   913  341913  
22   942  341913  
23   913  341913  
24  1254  341913  
25   996  341913  
26   580  341913  
27   111  341913  
28   313  341913  
29   674  341913