In [1]:
import numpy as np
import time


index = np.load("/home/jovyan/Sample_Based_Extension/UNSW/best_defense_indices.npy", allow_pickle=True)
index

array([['baseline', 0, 'Def1-11 Combined', 0.9923313825446824,
        0.9911800925969834, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9891551359556379,
        0.987484040917074, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9746251239350361,
        0.9705688736459472, array([1, 6, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9594545980995165,
        0.9538946564599001, array([6, 6, 6, ..., 6, 6, 6])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.919233840187416,
        0.9113183206844415, array([6, 6, 6, ..., 6, 6, 6])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9889357819094331,
        0.9872271983425641, array([9, 3, 9, ..., 9, 9, 9])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9680708250344385,
        0.9628361221532343, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9461968395469023,
        0.9384213027985543, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.3, 'Def1

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    ("DF", [0.1]),
    # ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    # ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [3]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1 and attack_name!= "CaFA" and attack_name!= "AutoPGD":
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '7' encode 6
defense '8' encode 7
defense '9' encode 8
defense '10' encode 9
defense '11' encode 10


In [5]:
# Collect 20% of eps = 0.1 data
from sklearn.model_selection import train_test_split

_, X_20, _ , y_20 = train_test_split(x_test_adv_0_1, y_label_0_1, test_size=0.2, stratify=y_label_0_1, random_state=42)


In [6]:
X_20.shape

(79780, 56)

In [7]:
from xgboost import XGBClassifier

print('xgb')
xgb20 = XGBClassifier()
xgb20.fit(X_20, y_20)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf20 = RandomForestClassifier()
rf20.fit(X_20, y_20)

print("DT")
from sklearn.tree import DecisionTreeClassifier
dt20 = DecisionTreeClassifier()
dt20.fit(X_20, y_20)

RF


RandomForestClassifier()

In [8]:
y_test = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

In [8]:
import numpy as np



from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = xgb20.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_Exclude2Attack/UNSW_Input20/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_Exclude2Attack/UNSW_Input20/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   108    235   1965   1895     18    216     71 109251    179     33]
(108, 56) (108,)
Save 0 to baseline_Def1.npy
(235, 56) (235,)
Save 1 to baseline_Def2.npy
(1965, 56) (1965,)
Save 2 to baseline_Def3.npy
(1895, 56) (1895,)
Save 3 to baseline_Def4.npy
(18, 56) (18,)
Save 4 to baseline_Def5.npy
(216, 56) (216,)
Save 5 to baseline_Def6.npy
(71, 56) (71,)
Save 7 to baseline_Def8.npy
(109251, 56) (109251,)
Save 8 to baseline_Def9.npy
(179, 56) (179,)
Save 9 to baseline_Def10.npy
(33, 56) (33,)
Save 10 to baseline_Def11.npy
Execution Time: 0.986542 seconds
(341913,)
[ 0  1  2  3  4  5  7  8  9 10] [ 71624    186    637    889    121 161471     66 106859     55      5]
(71624, 56) (71624,)
Save 0 to BIM_Def1.npy
(186, 56) (186,)
Save 1 to BIM_Def2.npy
(637, 56) (637,)
Save 2 to BIM_Def3.npy
(889, 56) (889,)
Save 3 to BIM_Def4.npy
(121, 56) (121,)
Save 4 to BIM_Def5.npy
(161471, 56) (161471,)
Save 5 to BIM_Def6.npy
(66, 56) (66,)
Save 7 to BIM_Def

In [9]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = rf20.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_Exclude2Attack/UNSW_Input20/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_Exclude2Attack/UNSW_Input20/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   217     89   1222   1216     16    252     57 110787     83     32]
(217, 56) (217,)
Save 0 to baseline_Def1.npy
(89, 56) (89,)
Save 1 to baseline_Def2.npy
(1222, 56) (1222,)
Save 2 to baseline_Def3.npy
(1216, 56) (1216,)
Save 3 to baseline_Def4.npy
(16, 56) (16,)
Save 4 to baseline_Def5.npy
(252, 56) (252,)
Save 5 to baseline_Def6.npy
(57, 56) (57,)
Save 7 to baseline_Def8.npy
(110787, 56) (110787,)
Save 8 to baseline_Def9.npy
(83, 56) (83,)
Save 9 to baseline_Def10.npy
(32, 56) (32,)
Save 10 to baseline_Def11.npy
Execution Time: 1.138480 seconds
(341913,)
[0 2 3 5 7 8] [ 52564    474    100 177264      2 111509]
(52564, 56) (52564,)
Save 0 to BIM_Def1.npy
(474, 56) (474,)
Save 2 to BIM_Def3.npy
(100, 56) (100,)
Save 3 to BIM_Def4.npy
(177264, 56) (177264,)
Save 5 to BIM_Def6.npy
(2, 56) (2,)
Save 7 to BIM_Def8.npy
(111509, 56) (111509,)
Save 8 to BIM_Def9.npy
Execution Time: 2.668098 seconds
(341913,)
[0 2 3 4 5 8] [ 42943    480     54  

In [10]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = dt20.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_Exclude2Attack/UNSW_Input20/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_Exclude2Attack/UNSW_Input20/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   375    515   2767   2129    107   1329    479 105773    304    193]
(375, 56) (375,)
Save 0 to baseline_Def1.npy
(515, 56) (515,)
Save 1 to baseline_Def2.npy
(2767, 56) (2767,)
Save 2 to baseline_Def3.npy
(2129, 56) (2129,)
Save 3 to baseline_Def4.npy
(107, 56) (107,)
Save 4 to baseline_Def5.npy
(1329, 56) (1329,)
Save 5 to baseline_Def6.npy
(479, 56) (479,)
Save 7 to baseline_Def8.npy
(105773, 56) (105773,)
Save 8 to baseline_Def9.npy
(304, 56) (304,)
Save 9 to baseline_Def10.npy
(193, 56) (193,)
Save 10 to baseline_Def11.npy
Execution Time: 0.618836 seconds
(341913,)
[ 0  1  2  3  4  5  6  7  8  9 10] [ 76509    719   8885   4027   1123 177509   6198   5811  60868    118
    146]
(76509, 56) (76509,)
Save 0 to BIM_Def1.npy
(719, 56) (719,)
Save 1 to BIM_Def2.npy
(8885, 56) (8885,)
Save 2 to BIM_Def3.npy
(4027, 56) (4027,)
Save 3 to BIM_Def4.npy
(1123, 56) (1123,)
Save 4 to BIM_Def5.npy
(177509, 56) (177509,)
Save 5 to BIM_Def6.npy
(6198, 

In [10]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}20")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/{m_name}_Exclude2Attack/UNSW_Input20/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [11]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input20_Exclude2Attack.csv")

In [12]:
all_attack_list

0      1    2     3     4    5       6    7      8       9    10  11  \
0   XGB10      0    0     0     0    0       0    0      0       0    0   0   
1   XGB10      0    0     0     0    0       0    0      0       0    0   0   
2   XGB10      0    0     0     0    0       0    0      0       0    0   0   
3   XGB10      0    0     0     0    0       0    0      0       0    0   0   
4   XGB10      0    0     0     0    0       0    0      0       0    0   0   
5   XGB10      0    0     0     0    0       0    0      0       0    0   0   
6   XGB10      0    0     0     0    0       0    0      0       0    0   0   
7   XGB10      0    0     0     0    0       0    0      0       0    0   0   
8   XGB10      0    0     0     0    0       0    0      0       0    0   0   
9   XGB10      0    0     0     0    0       0    0      0       0    0   0   
10   RF10    217   89  1222  1216   16     252    0     57  110787   83  32   
11   RF10  52564    0   474   100    0  177264    0      2  111509    0   0   
12   RF10  42943    0   480    54    2  187471    0      0  110963    0   0   
13   RF10  52564    0   474   100    0  177264    0      2  111509    0   0   
14   RF10  74029  330  2046   195  135  247143  737  15356    1669  236  37   
15   RF10  43918  180  2177  2567   48  174825    0    170  117776  186  66   
16   RF10    609  242  3485  3225   48     670    0    171  333140  227  96   
17   RF10  65985    8   502   185    0      55    0      0  275167    2   9   
18   RF10  50281    0    49    39    4  179323    0      0  112217    0   0   
19   RF10  39694    0   461    37    0  191091    0     48  110582    0   0   
20   DT10      0    0     0     0    0       0    0      0       0    0   0   
21   DT10      0    0     0     0    0       0    0      0       0    0   0   
22   DT10      0    0     0     0    0       0    0      0       0    0   0   
23   DT10      0    0     0     0    0       0    0      0       0    0   0   
24   DT10      0    0     0     0    0       0    0      0       0    0   0   
25   DT10      0    0     0     0    0       0    0      0       0    0   0   
26   DT10      0    0     0     0    0       0    0      0       0    0   0   
27   DT10      0    0     0     0    0       0    0      0       0    0   0   
28   DT10      0    0     0     0    0       0    0      0       0    0   0   
29   DT10      0    0     0     0    0       0    0      0       0    0   0   

        12  
0        0  
1        0  
2        0  
3        0  
4        0  
5        0  
6        0  
7        0  
8        0  
9        0  
10  113971  
11  341913  
12  341913  
13  341913  
14  341913  
15  341913  
16  341913  
17  341913  
18  341913  
19  341913  
20       0  
21       0  
22       0  
23       0  
24       0  
25       0  
26       0  
27       0  
28       0  
29       0