In [1]:
import numpy as np

index = np.load("/home/jovyan/Sample_Based_Extension/UNSW/best_defense_indices.npy", allow_pickle=True)
index

array([['baseline', 0, 'Def1-11 Combined', 0.9923313825446824,
        0.9911800925969834, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9891551359556379,
        0.987484040917074, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9746251239350361,
        0.9705688736459472, array([1, 6, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9594545980995165,
        0.9538946564599001, array([6, 6, 6, ..., 6, 6, 6])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.919233840187416,
        0.9113183206844415, array([6, 6, 6, ..., 6, 6, 6])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9889357819094331,
        0.9872271983425641, array([9, 3, 9, ..., 9, 9, 9])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9680708250344385,
        0.9628361221532343, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9461968395469023,
        0.9384213027985543, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.3, 'Def1

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    ("DF", [0.1]),
    ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [3]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1:
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '7' encode 6
defense '8' encode 7
defense '9' encode 8
defense '10' encode 9
defense '11' encode 10


In [5]:
from sklearn.ensemble import RandomForestClassifier
from scipy.stats import entropy
import numpy as np

def stratified_random_sample(X, y, fraction=None, count=None, random_state=42):
    assert (fraction is not None) ^ (count is not None), "Specify either fraction or count"

    rng = np.random.RandomState(seed=random_state)
    X_out, y_out = [], []

    for label in np.unique(y):
        X_c = X[y == label]
        y_c = y[y == label]

        n_total = len(X_c)
        n_sample = int(n_total * fraction) if fraction is not None else min(count, n_total)
        if n_sample == 0:
            n_sample = 1

        idx = rng.choice(n_total, size=n_sample, replace=False)

        X_out.append(X_c[idx])
        y_out.append(y_c[idx])

    return np.concatenate(X_out, axis=0), np.concatenate(y_out, axis=0)


def classwise_uncertainty_sampling_by_fraction(X_pool, y_pool, model, fraction=0.2, random_state=42):
    X_selected = []
    y_selected = []
    selected_indices = []

    classes = np.unique(y_pool)
    probs = model.predict_proba(X_pool)
    rng = np.random.RandomState(seed=random_state)

    for c in classes:
        idx_c = np.where(y_pool == c)[0]
        X_c = X_pool[idx_c]
        probs_c = probs[idx_c]


        n_c = len(idx_c)
        n_select = max(1, int(n_c * fraction))

        if n_c == 0:
            continue

        uncertainties = entropy(probs_c.T)  # shape: (n_samples_in_class,)
        sorted_idx = np.argsort(uncertainties)[-n_select:]  # top-k uncertain

        top_k_idx = idx_c[sorted_idx]

        selected_indices.extend(top_k_idx)
        X_selected.append(X_pool[top_k_idx])
        y_selected.append(y_pool[top_k_idx])

    selected_indices = np.array(selected_indices)
    X_selected = np.concatenate(X_selected, axis=0)
    y_selected = np.concatenate(y_selected, axis=0)

    remaining_idx = np.setdiff1d(np.arange(len(X_pool)), selected_indices)
    X_rest = X_pool[remaining_idx]
    y_rest = y_pool[remaining_idx]

    return X_rest, X_selected, y_rest, y_selected

X_pool = x_test_adv_0_1 
y_pool = y_label_0_1
X_train_init, y_train_init = stratified_random_sample(X_pool, y_pool, fraction=0.1, random_state=42)

clf = RandomForestClassifier(random_state=42)
clf.fit(X_train_init, y_train_init)


_, X_1, _, y_1 = classwise_uncertainty_sampling_by_fraction(
    x_test_adv_0_1, y_label_0_1, clf, fraction=0.01
)


In [6]:
X_1.shape

(10253, 56)

In [7]:
from xgboost import XGBClassifier

print('xgb')
xgb1 = XGBClassifier()
xgb1.fit(X_1, y_1)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier()
rf1.fit(X_1, y_1)

print("DT")
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier()
dt1.fit(X_1, y_1)

xgb
RF
DT


DecisionTreeClassifier()

In [8]:
import time
import numpy as np

y_test = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

base_path_template = "/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack}_eps_{eps}.npy"

from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = xgb1.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_ActiveLearning/UNSW_Input1/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_ActiveLearning/UNSW_Input1/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  6  7  8  9 10] [111436      7     34     70      4    954      1     32   1417     12
      4]
(111436, 56) (111436,)
Save 0 to baseline_Def1.npy
(7, 56) (7,)
Save 1 to baseline_Def2.npy
(34, 56) (34,)
Save 2 to baseline_Def3.npy
(70, 56) (70,)
Save 3 to baseline_Def4.npy
(4, 56) (4,)
Save 4 to baseline_Def5.npy
(954, 56) (954,)
Save 5 to baseline_Def6.npy
(1, 56) (1,)
Save 6 to baseline_Def7.npy
(32, 56) (32,)
Save 7 to baseline_Def8.npy
(1417, 56) (1417,)
Save 8 to baseline_Def9.npy
(12, 56) (12,)
Save 9 to baseline_Def10.npy
(4, 56) (4,)
Save 10 to baseline_Def11.npy
Execution Time: 0.929804 seconds
(341913,)
[0 2 3 4 5 6 7 8] [301297      1    275     22   2807      2      3  37506]
(301297, 56) (301297,)
Save 0 to BIM_Def1.npy
(1, 56) (1,)
Save 2 to BIM_Def3.npy
(275, 56) (275,)
Save 3 to BIM_Def4.npy
(22, 56) (22,)
Save 4 to BIM_Def5.npy
(2807, 56) (2807,)
Save 5 to BIM_Def6.npy
(2, 56) (2,)
Save 6 to BIM_Def7.npy
(3, 56) (3,)
Save 7 to BIM_Def8.npy


In [9]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = rf1.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_ActiveLearning/UNSW_Input1/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_ActiveLearning/UNSW_Input1/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  6  7  8  9 10] [111889      3     30     40      3    742      1     31   1224      4
      4]
(111889, 56) (111889,)
Save 0 to baseline_Def1.npy
(3, 56) (3,)
Save 1 to baseline_Def2.npy
(30, 56) (30,)
Save 2 to baseline_Def3.npy
(40, 56) (40,)
Save 3 to baseline_Def4.npy
(3, 56) (3,)
Save 4 to baseline_Def5.npy
(742, 56) (742,)
Save 5 to baseline_Def6.npy
(1, 56) (1,)
Save 6 to baseline_Def7.npy
(31, 56) (31,)
Save 7 to baseline_Def8.npy
(1224, 56) (1224,)
Save 8 to baseline_Def9.npy
(4, 56) (4,)
Save 9 to baseline_Def10.npy
(4, 56) (4,)
Save 10 to baseline_Def11.npy
Execution Time: 1.168470 seconds
(341913,)
[ 0  1  2  3  4  5  6  8  9 10] [333809      1      1     52      1    334      1   7708      5      1]
(333809, 56) (333809,)
Save 0 to BIM_Def1.npy
(1, 56) (1,)
Save 1 to BIM_Def2.npy
(1, 56) (1,)
Save 2 to BIM_Def3.npy
(52, 56) (52,)
Save 3 to BIM_Def4.npy
(1, 56) (1,)
Save 4 to BIM_Def5.npy
(334, 56) (334,)
Save 5 to BIM_Def6.npy
(1, 56) (1,)
Sav

In [11]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = dt1.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_ActiveLearning/UNSW_Input1/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_ActiveLearning/UNSW_Input1/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  6  7  8  9 10] [96287    72    49   129   277  6399     6    52 10684    10     6]
(96287, 56) (96287,)
Save 0 to baseline_Def1.npy
(72, 56) (72,)
Save 1 to baseline_Def2.npy
(49, 56) (49,)
Save 2 to baseline_Def3.npy
(129, 56) (129,)
Save 3 to baseline_Def4.npy
(277, 56) (277,)
Save 4 to baseline_Def5.npy
(6399, 56) (6399,)
Save 5 to baseline_Def6.npy
(6, 56) (6,)
Save 6 to baseline_Def7.npy
(52, 56) (52,)
Save 7 to baseline_Def8.npy
(10684, 56) (10684,)
Save 8 to baseline_Def9.npy
(10, 56) (10,)
Save 9 to baseline_Def10.npy
(6, 56) (6,)
Save 10 to baseline_Def11.npy
Execution Time: 0.068058 seconds
(341913,)
[ 0  1  2  3  4  5  6  7  8  9 10] [280768    161    433   4568    254  18813     93    178  36627      3
     15]
(280768, 56) (280768,)
Save 0 to BIM_Def1.npy
(161, 56) (161,)
Save 1 to BIM_Def2.npy
(433, 56) (433,)
Save 2 to BIM_Def3.npy
(4568, 56) (4568,)
Save 3 to BIM_Def4.npy
(254, 56) (254,)
Save 4 to BIM_Def5.npy
(18813, 56) (18813,)
Save 5 t

In [12]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}1")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/{m_name}_ActiveLearning/UNSW_Input1/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [13]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input1_ActiveLearning.csv")

In [14]:
all_attack_list

0       1    2     3      4    5      6     7    8      9   10   11  \
0   XGB1  111436    7    34     70    4    954     1   32   1417  12    4   
1   XGB1  301297    0     1    275   22   2807     2    3  37506   0    0   
2   XGB1  299746    0     1    201   21   3493     2    2  38447   0    0   
3   XGB1  301297    0     1    275   22   2807     2    3  37506   0    0   
4   XGB1  338665    0    20      1    0   2540    22   63    597   5    0   
5   XGB1  328859   21    99    317   42   4930     1   93   7506  33   12   
6   XGB1  329911   21   107    256   12   2635     4   96   8817  42   12   
7   XGB1  340279    0     8    277    0    860     1    4    484   0    0   
8   XGB1  303009    0     1    270   27   1717     0    0  36888   0    1   
9   XGB1  300440    0    46    256   50   3258     2    2  37854   5    0   
10   RF1  111889    3    30     40    3    742     1   31   1224   4    4   
11   RF1  333809    1     1     52    1    334     1    0   7708   5    1   
12   RF1  334042    1     2     47    5    515     2    0   7293   5    1   
13   RF1  333809    1     1     52    1    334     1    0   7708   5    1   
14   RF1  339883    0     4      0    0   1645     9   40    332   0    0   
15   RF1  336918    9    78    100    9   2061     1   90   2618  17   12   
16   RF1  334024    9    83    141    9   2095     3   93   5426  18   12   
17   RF1  340927    0     0     45    0    473     1    2    465   0    0   
18   RF1  335361    1     0     48    1    122     1    0   6378   0    1   
19   RF1  333477    1     3     43   12    785     1    0   7585   5    1   
20   DT1   96287   72    49    129  277   6399     6   52  10684  10    6   
21   DT1  280768  161   433   4568  254  18813    93  178  36627   3   15   
22   DT1  291202  185   364   3328  362  16924  2446  146  26934   3   19   
23   DT1  280768  161   433   4568  254  18813    93  178  36627   3   15   
24   DT1  255585  154   138   1633  118  66585   603  344  16734   3   16   
25   DT1  265982  334  1724   7390  799  28085    99  336  37121  11   32   
26   DT1  289120  216   158    753  819  18067    33  161  32535  33   18   
27   DT1  281099   76    11  10483    5  37820    31  128  12071   4  185   
28   DT1  279392  182   199   6480  363  18994   111  406  35702   1   83   
29   DT1  278226  199   365   6649  435  20545    45  159  35257   7   26   

        12  
0   113971  
1   341913  
2   341913  
3   341913  
4   341913  
5   341913  
6   341913  
7   341913  
8   341913  
9   341913  
10  113971  
11  341913  
12  341913  
13  341913  
14  341913  
15  341913  
16  341913  
17  341913  
18  341913  
19  341913  
20  113971  
21  341913  
22  341913  
23  341913  
24  341913  
25  341913  
26  341913  
27  341913  
28  341913  
29  341913