In [1]:
import numpy as np

index = np.load("/home/jovyan/Sample_Based_Extension/UNSW/best_defense_indices.npy", allow_pickle=True)
index

array([['baseline', 0, 'Def1-11 Combined', 0.9923313825446824,
        0.9911800925969834, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9891551359556379,
        0.987484040917074, array([9, 3, 9, ..., 9, 9, 9])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9746251239350361,
        0.9705688736459472, array([1, 6, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9594545980995165,
        0.9538946564599001, array([6, 6, 6, ..., 6, 6, 6])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.919233840187416,
        0.9113183206844415, array([6, 6, 6, ..., 6, 6, 6])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9889357819094331,
        0.9872271983425641, array([9, 3, 9, ..., 9, 9, 9])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9680708250344385,
        0.9628361221532343, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9461968395469023,
        0.9384213027985543, array([1, 6, 1, ..., 1, 1, 1])],
       ['FGSM', 0.3, 'Def1

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    ("DF", [0.1]),
    # ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    # ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [3]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1 and attack_name!= "CaFA" and attack_name!= "AutoPGD":
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '7' encode 6
defense '8' encode 7
defense '9' encode 8
defense '10' encode 9
defense '11' encode 10


In [5]:
# Collect 10% of eps = 0.1 data
from sklearn.model_selection import train_test_split

_, X_10, _ , y_10 = train_test_split(x_test_adv_0_1, y_label_0_1, test_size=0.1, stratify=y_label_0_1, random_state=42)


In [6]:
X_10.shape

(159560, 56)

In [7]:
# from xgboost import XGBClassifier

# print('xgb')
# xgb10 = XGBClassifier()
# xgb10.fit(X_10, y_10)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf10 = RandomForestClassifier()
rf10.fit(X_10, y_10)

# print("DT")
# from sklearn.tree import DecisionTreeClassifier
# dt10 = DecisionTreeClassifier()
# dt10.fit(X_10, y_10)

xgb
RF
DT


DecisionTreeClassifier()

In [ ]:
import time
import numpy as np

y_test = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

In [8]:


# base_path_template = "/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack}_eps_{eps}.npy"

# from sklearn.model_selection import train_test_split

# for attack_name, epsilons in attack_models:
#     start_time = time.time()
#     all_adv_examples = []
#     all_y = []
    
#     if attack_name != "baseline":
#         for epsilon in epsilons:
#             filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
#             x_test_adv = np.load(filename)
#             all_adv_examples.append(x_test_adv)
#             all_y.append(y_test)
    
#         X = np.concatenate(all_adv_examples, axis=0)
#         y = np.concatenate(all_y, axis=0)
#     else:
#         X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
#         y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

#     y_pred = xgb10.predict(X)
#     print(y_pred.shape)
#     unique_classes, count = np.unique(y_pred, return_counts=True)
#     print(unique_classes, count)
#     for class_num in unique_classes:
#         indices = np.where(y_pred == class_num)[0]
#         X_class = X[indices]
#         y_class = y[indices]
#         print(X_class.shape, y_class.shape)
    
#         x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_Exclude2Attack/UNSW_Input10/x_test_adv_{attack_name}_Def{class_num+1}.npy"
#         y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/XGB_Exclude2Attack/UNSW_Input10/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
#         np.save(x_filename, X_class)
#         np.save(y_filename, y_class)
    
#         print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

#     end_time = time.time()
#     result = end_time - start_time
#     print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   108    235   1965   1895     18    216     71 109251    179     33]
(108, 56) (108,)
Save 0 to baseline_Def1.npy
(235, 56) (235,)
Save 1 to baseline_Def2.npy
(1965, 56) (1965,)
Save 2 to baseline_Def3.npy
(1895, 56) (1895,)
Save 3 to baseline_Def4.npy
(18, 56) (18,)
Save 4 to baseline_Def5.npy
(216, 56) (216,)
Save 5 to baseline_Def6.npy
(71, 56) (71,)
Save 7 to baseline_Def8.npy
(109251, 56) (109251,)
Save 8 to baseline_Def9.npy
(179, 56) (179,)
Save 9 to baseline_Def10.npy
(33, 56) (33,)
Save 10 to baseline_Def11.npy
Execution Time: 0.986542 seconds
(341913,)
[ 0  1  2  3  4  5  7  8  9 10] [ 71624    186    637    889    121 161471     66 106859     55      5]
(71624, 56) (71624,)
Save 0 to BIM_Def1.npy
(186, 56) (186,)
Save 1 to BIM_Def2.npy
(637, 56) (637,)
Save 2 to BIM_Def3.npy
(889, 56) (889,)
Save 3 to BIM_Def4.npy
(121, 56) (121,)
Save 4 to BIM_Def5.npy
(161471, 56) (161471,)
Save 5 to BIM_Def6.npy
(66, 56) (66,)
Save 7 to BIM_Def

In [9]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

    y_pred = rf10.predict(X)
    print(y_pred.shape)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_Exclude2Attack/UNSW_Input10/x_test_adv_{attack_name}_Def{class_num+1}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/RF_Exclude2Attack/UNSW_Input10/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   225    153   1585   1639     24    480    102 109591    135     37]
(225, 56) (225,)
Save 0 to baseline_Def1.npy
(153, 56) (153,)
Save 1 to baseline_Def2.npy
(1585, 56) (1585,)
Save 2 to baseline_Def3.npy
(1639, 56) (1639,)
Save 3 to baseline_Def4.npy
(24, 56) (24,)
Save 4 to baseline_Def5.npy
(480, 56) (480,)
Save 5 to baseline_Def6.npy
(102, 56) (102,)
Save 7 to baseline_Def8.npy
(109591, 56) (109591,)
Save 8 to baseline_Def9.npy
(135, 56) (135,)
Save 9 to baseline_Def10.npy
(37, 56) (37,)
Save 10 to baseline_Def11.npy
Execution Time: 1.754252 seconds
(341913,)
[0 2 3 5 7 8] [ 43282    536     83 185061      4 112947]
(43282, 56) (43282,)
Save 0 to BIM_Def1.npy
(536, 56) (536,)
Save 2 to BIM_Def3.npy
(83, 56) (83,)
Save 3 to BIM_Def4.npy
(185061, 56) (185061,)
Save 5 to BIM_Def6.npy
(4, 56) (4,)
Save 7 to BIM_Def8.npy
(112947, 56) (112947,)
Save 8 to BIM_Def9.npy
Execution Time: 3.349355 seconds
(341913,)
[0 2 3 5 7 8] [ 44892    511     

In [10]:
# from sklearn.model_selection import train_test_split

# for attack_name, epsilons in attack_models:
#     start_time = time.time()
#     all_adv_examples = []
#     all_y = []
    
#     if attack_name != "baseline":
#         for epsilon in epsilons:
#             filename = f'/home/jovyan/Sample_Based_Extension/UNSW/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
#             x_test_adv = np.load(filename)
#             all_adv_examples.append(x_test_adv)
#             all_y.append(y_test)
    
#         X = np.concatenate(all_adv_examples, axis=0)
#         y = np.concatenate(all_y, axis=0)
#     else:
#         X = np.load('/home/jovyan/Sample_Based_Extension/UNSW/x_test.npy')
#         y = np.load('/home/jovyan/Sample_Based_Extension/UNSW/y_test.npy')

#     y_pred = dt10.predict(X)
#     print(y_pred.shape)
#     unique_classes, count = np.unique(y_pred, return_counts=True)
#     print(unique_classes, count)
#     for class_num in unique_classes:
#         indices = np.where(y_pred == class_num)[0]
#         X_class = X[indices]
#         y_class = y[indices]
#         print(X_class.shape, y_class.shape)
    
#         x_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_Exclude2Attack/UNSW_Input10/x_test_adv_{attack_name}_Def{class_num+1}.npy"
#         y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/DT_Exclude2Attack/UNSW_Input10/y_test_adv_{attack_name}_Def{class_num+1}.npy"
        
#         np.save(x_filename, X_class)
#         np.save(y_filename, y_class)
    
#         print(f"Save {class_num} to {attack_name}_Def{class_num+1}.npy")

#     end_time = time.time()
#     result = end_time - start_time
#     print(f"Execution Time: {result:.6f} seconds")
    

(113971,)
[ 0  1  2  3  4  5  7  8  9 10] [   375    515   2767   2129    107   1329    479 105773    304    193]
(375, 56) (375,)
Save 0 to baseline_Def1.npy
(515, 56) (515,)
Save 1 to baseline_Def2.npy
(2767, 56) (2767,)
Save 2 to baseline_Def3.npy
(2129, 56) (2129,)
Save 3 to baseline_Def4.npy
(107, 56) (107,)
Save 4 to baseline_Def5.npy
(1329, 56) (1329,)
Save 5 to baseline_Def6.npy
(479, 56) (479,)
Save 7 to baseline_Def8.npy
(105773, 56) (105773,)
Save 8 to baseline_Def9.npy
(304, 56) (304,)
Save 9 to baseline_Def10.npy
(193, 56) (193,)
Save 10 to baseline_Def11.npy
Execution Time: 0.618836 seconds
(341913,)
[ 0  1  2  3  4  5  6  7  8  9 10] [ 76509    719   8885   4027   1123 177509   6198   5811  60868    118
    146]
(76509, 56) (76509,)
Save 0 to BIM_Def1.npy
(719, 56) (719,)
Save 1 to BIM_Def2.npy
(8885, 56) (8885,)
Save 2 to BIM_Def3.npy
(4027, 56) (4027,)
Save 3 to BIM_Def4.npy
(1123, 56) (1123,)
Save 4 to BIM_Def5.npy
(177509, 56) (177509,)
Save 5 to BIM_Def6.npy
(6198, 

In [11]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}10")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/UNSW/UNSW_Dynamite_Selection_Data/{m_name}_Exclude2Attack/UNSW_Input10/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [12]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input10_Exclude2Attack.csv")

In [13]:
all_attack_list

0       1     2      3       4     5       6     7      8       9   \
0   XGB20     108   235   1965    1895    18     216     0     71  109251   
1   XGB20   71624   186    637     889   121  161471     0     66  106859   
2   XGB20   61433    17    537    1349   123  171638     4    729  106044   
3   XGB20   71624   186    637     889   121  161471     0     66  106859   
4   XGB20   74465   526   2278     294   242  244596   466  17208    1541   
5   XGB20   69200   607   3791    4217   127  160138     0    204  103098   
6   XGB20     398   653   5695    5200    54     733     0    212  328388   
7   XGB20   40879    51    793    2053     7      93     0      9  297985   
8   XGB20   76790   121    802    1215   186  151471     0    104  111176   
9   XGB20   63664    17    782     968   252  166460     0     77  109634   
10   RF20     225   153   1585    1639    24     480     0    102  109591   
11   RF20   43282     0    536      83     8  185061     0      4  112947   
12   RF20   44892     0    511      48     3  183586     1      6  112870   
13   RF20   43282     0    536      83     8  185061     0      4  112947   
14   RF20   74400   501   2188     256   119  245324   429  16391    1984   
15   RF20   31885   333   3141    3514    72  186199     0    280  116066   
16   RF20     613   431   4748    4340    72    1243     0    306  329683   
17   RF20   40292    13    421     362     0     106     0      4  300704   
18   RF20   43008     5    166      28     3  185077     0      0  113631   
19   RF20   31607     0    512      34     4  196962     0     30  112768   
20   DT20     375   515   2767    2129   107    1329     5    479  105773   
21   DT20   76509   719   8885    4027  1123  177509  6198   5811   60868   
22   DT20  114437   157   7225    3780   330  135438  9799  10076   60406   
23   DT20   76509   719   8885    4027  1123  177509  6198   5811   60868   
24   DT20   71521   692   2472    1082  1917  241495  1313  18032    2655   
25   DT20   75646  1222  12240    7712  1771  168794  5406   4429   63722   
26   DT20    1428  1439   8100    6213   276    3739     1   1418  317950   
27   DT20   71845  5969   4479  109457  6287    4469     8    560  138256   
28   DT20  100817   666   5569    7131  3683  166935   568   6555   49820   
29   DT20   84296   301   4863    6469  1184  166373  9609   5958   62532   

     10   11      12  
0   179   33  113971  
1    55    5  341913  
2     3   36  341913  
3    55    5  341913  
4   234   63  341913  
5   440   91  341913  
6   482   98  341913  
7    21   22  341913  
8    44    4  341913  
9    25   34  341913  
10  135   37  113971  
11    0    0  341921  
12    0    0  341917  
13    0    0  341921  
14  257   64  341913  
15  327   96  341913  
16  368  109  341913  
17    4    7  341913  
18    0    0  341918  
19    0    0  341917  
20  304  193  113976  
21  118  146  341913  
22   82  183  341913  
23  118  146  341913  
24  424  310  341913  
25  594  377  341913  
26  808  541  341913  
27  450  141  341921  
28   53  116  341913  
29   84  244  341913