In [1]:
import numpy as np

index = np.load("/home/jovyan/Sample_Based_Extension/WUSTL/best_defense_indices.npy", allow_pickle=True)
index


array([['baseline', 0, 'Def1-11 Combined', 0.9999916231419081,
        0.9951091814583067, array([2, 2, 2, ..., 2, 2, 2])],
       ['BIM', 0.01, 'Def1-11 Combined', 0.9999916231419081,
        0.9951091814583067, array([2, 2, 2, ..., 2, 2, 2])],
       ['BIM', 0.1, 'Def1-11 Combined', 0.9998827239867143,
        0.9600649800293866, array([1, 1, 1, ..., 1, 1, 1])],
       ['BIM', 0.2, 'Def1-11 Combined', 0.9996984331086939,
        0.9305545272093338, array([3, 3, 3, ..., 3, 3, 3])],
       ['BIM', 0.3, 'Def1-11 Combined', 0.9984796002563319,
        0.7518383136072314, array([5, 5, 5, ..., 5, 5, 5])],
       ['FGSM', 0.01, 'Def1-11 Combined', 0.9999916231419081,
        0.9951091814583067, array([2, 2, 2, ..., 2, 2, 2])],
       ['FGSM', 0.1, 'Def1-11 Combined', 0.9998701586995765,
        0.939002641264322, array([1, 1, 1, ..., 1, 1, 1])],
       ['FGSM', 0.2, 'Def1-11 Combined', 0.9971518682487759,
        0.8894642081911899, array([3, 3, 3, ..., 3, 3, 3])],
       ['FGSM', 0.3, 'Def

In [2]:
attack_models = [
    ("BIM", [0.1]),
    ("FGSM", [0.1]),
    ("PGD", [0.1]),
    ("DF", [0.1]),
    # ("AutoPGD", [0.1]),
    ("ZOO", [0.1]),
    # ("CaFA", [0.1]),
    ("SINIFGSM", [0.1]),
    ("VNIFGSM", [0.1]),
]

all_adv_examples = []

for attack_name, epsilons in attack_models:
    for epsilon in epsilons:
        filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
        x_test_adv = np.load(filename)
        all_adv_examples.append(x_test_adv)

x_test_adv_0_1 = np.concatenate(all_adv_examples, axis=0)


In [3]:
y_labels = []

for row in index:
    attack_name, eps = row[0], row[1]
    if eps == 0.1 and attack_name!= "CaFA" and attack_name!= "AutoPGD":
        y_array = row[-1]
        y_labels.append(y_array)

y_label_0_1 = np.concatenate(y_labels, axis=0)

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_label_0_1)

y_label_0_1 = label_encoder.transform(y_label_0_1)

for index, class_label in enumerate(label_encoder.classes_):
    print(f"defense '{class_label}' encode {index}")

defense '1' encode 0
defense '2' encode 1
defense '3' encode 2
defense '4' encode 3
defense '5' encode 4
defense '6' encode 5
defense '7' encode 6
defense '8' encode 7
defense '9' encode 8
defense '10' encode 9


In [5]:
x_test_adv_0_1.shape

(1671271, 42)

In [6]:
from xgboost import XGBClassifier

print('xgb')
xgb100 = XGBClassifier()
xgb100.fit(x_test_adv_0_1, y_label_0_1)

print("RF")
from sklearn.ensemble import RandomForestClassifier
rf100 = RandomForestClassifier()
rf100.fit(x_test_adv_0_1, y_label_0_1)

# print("DT")
# from sklearn.tree import DecisionTreeClassifier
# dt100 = DecisionTreeClassifier()
# dt100.fit(x_test_adv_0_1, y_label_0_1)

xgb
RF


RandomForestClassifier()

In [7]:
import time
import numpy as np

y_test = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

attack_models = [
    ("baseline", [0]),
    ("BIM", [0.01, 0.2, 0.3]),
    ("FGSM", [0.01, 0.2, 0.3]),
    ("PGD", [0.01, 0.2, 0.3]),
    ("DF", [0.01, 0.2, 0.3]),
    ("AutoPGD", [0.01, 0.2, 0.3]),
    ("ZOO", [0.01, 0.2, 0.3]),
    ("CaFA", [0.01, 0.2, 0.3]),
    ("SINIFGSM", [0.01, 0.2, 0.3]),
    ("VNIFGSM", [0.01, 0.2, 0.3]),
]

In [8]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

    y_pred = xgb100.predict(X)
    print(y_pred.shape)
    y_pred = label_encoder.inverse_transform(y_pred)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/XGB_Exclude2Attack/WUSTL_Input100/x_test_adv_{attack_name}_Def{class_num}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/XGB_Exclude2Attack/WUSTL_Input100/y_test_adv_{attack_name}_Def{class_num}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(238753,)
[1 2 3 4 5] [     5      2      2      1 238743]
(5, 42) (5,)
Save 1 to baseline_Def2.npy
(2, 42) (2,)
Save 2 to baseline_Def3.npy
(2, 42) (2,)
Save 3 to baseline_Def4.npy
(1, 42) (1,)
Save 4 to baseline_Def5.npy
(238743, 42) (238743,)
Save 5 to baseline_Def6.npy
Execution Time: 2.382942 seconds
(716259,)
[0 2 4 5 6 8 9] [210826  24148   2086 474662      1   2040   2496]
(210826, 42) (210826,)
Save 0 to BIM_Def1.npy
(24148, 42) (24148,)
Save 2 to BIM_Def3.npy
(2086, 42) (2086,)
Save 4 to BIM_Def5.npy
(474662, 42) (474662,)
Save 5 to BIM_Def6.npy
(1, 42) (1,)
Save 6 to BIM_Def7.npy
(2040, 42) (2040,)
Save 8 to BIM_Def9.npy
(2496, 42) (2496,)
Save 9 to BIM_Def10.npy
Execution Time: 4.390656 seconds
(716259,)
[0 1 2 3 4 5 7 8 9] [  8732      4 405705      1   6332 288975    519    329   5662]
(8732, 42) (8732,)
Save 0 to FGSM_Def1.npy
(4, 42) (4,)
Save 1 to FGSM_Def2.npy
(405705, 42) (405705,)
Save 2 to FGSM_Def3.npy
(1, 42) (1,)
Save 3 to FGSM_Def4.npy
(6332, 42) (6332,)
Save 4

In [9]:
from sklearn.model_selection import train_test_split

for attack_name, epsilons in attack_models:
    start_time = time.time()
    all_adv_examples = []
    all_y = []
    
    if attack_name != "baseline":
        for epsilon in epsilons:
            filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
            x_test_adv = np.load(filename)
            all_adv_examples.append(x_test_adv)
            all_y.append(y_test)
    
        X = np.concatenate(all_adv_examples, axis=0)
        y = np.concatenate(all_y, axis=0)
    else:
        X = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/x_test.npy')
        y = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

    y_pred = rf100.predict(X)
    print(y_pred.shape)
    y_pred = label_encoder.inverse_transform(y_pred)
    unique_classes, count = np.unique(y_pred, return_counts=True)
    print(unique_classes, count)
    for class_num in unique_classes:
        indices = np.where(y_pred == class_num)[0]
        X_class = X[indices]
        y_class = y[indices]
        print(X_class.shape, y_class.shape)
    
        x_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/RF_Exclude2Attack/WUSTL_Input100/x_test_adv_{attack_name}_Def{class_num}.npy"
        y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/RF_Exclude2Attack/WUSTL_Input100/y_test_adv_{attack_name}_Def{class_num}.npy"
        
        np.save(x_filename, X_class)
        np.save(y_filename, y_class)
    
        print(f"Save {class_num} to {attack_name}_Def{class_num}.npy")

    end_time = time.time()
    result = end_time - start_time
    print(f"Execution Time: {result:.6f} seconds")
    

(238753,)
[1 2 3 4 5] [    10      2      1      1 238739]
(10, 42) (10,)
Save 1 to baseline_Def2.npy
(2, 42) (2,)
Save 2 to baseline_Def3.npy
(1, 42) (1,)
Save 3 to baseline_Def4.npy
(1, 42) (1,)
Save 4 to baseline_Def5.npy
(238739, 42) (238739,)
Save 5 to baseline_Def6.npy
Execution Time: 1.425642 seconds
(716259,)
[0 1 2 4 5] [  8252   1084  33459   1314 672150]
(8252, 42) (8252,)
Save 0 to BIM_Def1.npy
(1084, 42) (1084,)
Save 1 to BIM_Def2.npy
(33459, 42) (33459,)
Save 2 to BIM_Def3.npy
(1314, 42) (1314,)
Save 4 to BIM_Def5.npy
(672150, 42) (672150,)
Save 5 to BIM_Def6.npy
Execution Time: 4.596476 seconds
(716259,)
[0 1 2 4 5 8 9] [253505    686  11839   5791 442787     34   1617]
(253505, 42) (253505,)
Save 0 to FGSM_Def1.npy
(686, 42) (686,)
Save 1 to FGSM_Def2.npy
(11839, 42) (11839,)
Save 2 to FGSM_Def3.npy
(5791, 42) (5791,)
Save 4 to FGSM_Def5.npy
(442787, 42) (442787,)
Save 5 to FGSM_Def6.npy
(34, 42) (34,)
Save 8 to FGSM_Def9.npy
(1617, 42) (1617,)
Save 9 to FGSM_Def10.npy


In [10]:
# from sklearn.model_selection import train_test_split

# for attack_name, epsilons in attack_models:
#     start_time = time.time()
#     all_adv_examples = []
#     all_y = []
    
#     if attack_name != "baseline":
#         for epsilon in epsilons:
#             filename = f'/home/jovyan/Sample_Based_Extension/WUSTL/transfer_attack/x_test_adv_{attack_name}_eps_{epsilon}.npy'
#             x_test_adv = np.load(filename)
#             all_adv_examples.append(x_test_adv)
#             all_y.append(y_test)
    
#         X = np.concatenate(all_adv_examples, axis=0)
#         y = np.concatenate(all_y, axis=0)
#     else:
#         X = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/x_test.npy')
#         y = np.load('/home/jovyan/Sample_Based_Extension/WUSTL/y_test.npy')

#     y_pred = dt100.predict(X)
#     print(y_pred.shape)
#     y_pred = label_encoder.inverse_transform(y_pred)
#     unique_classes, count = np.unique(y_pred, return_counts=True)
#     print(unique_classes, count)
#     for class_num in unique_classes:
#         indices = np.where(y_pred == class_num)[0]
#         X_class = X[indices]
#         y_class = y[indices]
#         print(X_class.shape, y_class.shape)
    
#         x_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/DT_Exclude2Attack/WUSTL_Input100/x_test_adv_{attack_name}_Def{class_num}.npy"
#         y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/DT_Exclude2Attack/WUSTL_Input100/y_test_adv_{attack_name}_Def{class_num}.npy"
        
#         np.save(x_filename, X_class)
#         np.save(y_filename, y_class)
    
#         print(f"Save {class_num} to {attack_name}_Def{class_num}.npy")

#     end_time = time.time()
#     result = end_time - start_time
#     print(f"Execution Time: {result:.6f} seconds")
    

In [11]:
import numpy as np


attack_names = [
    "baseline", 
    "BIM", "FGSM", "PGD", "DF",
    "AutoPGD", "ZOO", "CaFA", "SINIFGSM", "VNIFGSM"
]

all_attack_list = []

model_name_list = ["XGB", "RF", "DT"]

for m_name in model_name_list:
    for attack_name in attack_names:
        each = []
        num = 0
        each.append(f"{m_name}100")
        for i in range(1, 12):
            y_filename = f"/home/jovyan/Sample_Based_Extension/WUSTL/WUSTL_Dynamite_Selection_Data/{m_name}_Exclude2Attack/WUSTL_Input100/x_test_adv_{attack_name}_Def{i}.npy"
            try:
                y = np.load(y_filename)
                num+=y.shape[0]
                each.append(y.shape[0])
            except FileNotFoundError:
                each.append(0)
        each.append(num)
        all_attack_list.append(each)


In [12]:
import pandas as pd
all_attack_list = pd.DataFrame(all_attack_list)
all_attack_list.to_csv("./Dynamite_Num_Attack_Input100_Exclude2Attack.csv")

In [13]:
all_attack_list

0       1      2       3   4     5       6    7     8      9      10  \
0   XGB100       0      5       2   2     1  238743    0     0      0      0   
1   XGB100  210826      0   24148   0  2086  474662    1     0   2040   2496   
2   XGB100    8732      4  405705   1  6332  288975    0   519    329   5662   
3   XGB100  210826      0   24148   0  2086  474662    1     0   2040   2496   
4   XGB100      88      0    6003   0  9795  688058    5  3241    217   8852   
5   XGB100  262103      3   43978   2   867  403070    1    41   3218   2976   
6   XGB100       0     15       3   6     4  716231    0     0      0      0   
7   XGB100  201626  11224   13487  49   945  454349  174     2  30020   4383   
8   XGB100    6176      0  473370   0   200  236258    0     0     68    187   
9   XGB100   96109      0   66679  81   334  548968    0     0   3035   1053   
10   RF100       0     10       2   1     1  238739    0     0      0      0   
11   RF100    8252   1084   33459   0  1314  672150    0     0      0      0   
12   RF100  253505    686   11839   0  5791  442787    0     0     34   1617   
13   RF100    8252   1084   33459   0  1314  672150    0     0      0      0   
14   RF100      83      0    5880  34  8529  688031    0  3215    198  10289   
15   RF100  204773    217   34924   0   329  476004    0     0      0     12   
16   RF100       0     32       5   3     3  716216    0     0      0      0   
17   RF100  244537      0       7   0     0  471715    0     0      0      0   
18   RF100   44146  18967  429261   0     0  223885    0     0      0      0   
19   RF100  201826  31360   20072   5  5335  457651    0     0      0     10   
20   DT100       0      0       0   0     0       0    0     0      0      0   
21   DT100       0      0       0   0     0       0    0     0      0      0   
22   DT100       0      0       0   0     0       0    0     0      0      0   
23   DT100       0      0       0   0     0       0    0     0      0      0   
24   DT100       0      0       0   0     0       0    0     0      0      0   
25   DT100       0      0       0   0     0       0    0     0      0      0   
26   DT100       0      0       0   0     0       0    0     0      0      0   
27   DT100       0      0       0   0     0       0    0     0      0      0   
28   DT100       0      0       0   0     0       0    0     0      0      0   
29   DT100       0      0       0   0     0       0    0     0      0      0   

    11      12  
0    0  238753  
1    0  716259  
2    0  716259  
3    0  716259  
4    0  716259  
5    0  716259  
6    0  716259  
7    0  716259  
8    0  716259  
9    0  716259  
10   0  238753  
11   0  716259  
12   0  716259  
13   0  716259  
14   0  716259  
15   0  716259  
16   0  716259  
17   0  716259  
18   0  716259  
19   0  716259  
20   0       0  
21   0       0  
22   0       0  
23   0       0  
24   0       0  
25   0       0  
26   0       0  
27   0       0  
28   0       0  
29   0       0